### ISSUE TITLE
Замечания по лабораторной работе №5 (1 этап)

### ISSUE THREAD

**Issue by volgatech-web-development** [AkshachRd/web-development#1]
- [x] Уехали блоки 
![image](https://user-images.githubusercontent.com/63309827/78864464-57587080-7a44-11ea-96c2-3292d0335850.png)

- [x] В экран не помещается содержимое, его нужно отформатировать 
```
<p class="second_phrase">
    Он регулярно посещал вечерние лекции местного профессора и, разумеется, всегда 
    засыпал на самом интересном месте. А когда просыпался, то обнаруживал себя в каком- 
    нибудь параллельном мире, где один из основных законов физики действовал не так, как в 
    его мире.
</p>
<a class="green_write" href="https://twitter.com/Ponasenkov ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor">
    <span class="green_underline">Напиши мне</span> →
</a>
```
То же самое сделать для <p> с классом first_phrase

- [x]  Сокращения в именованиях классов не используем ```.right_block_rtl```. Убрать сокращения во  всех названиях классов

- [x] ```font: Bold 16px/2.63 'Open Sans';``` bold пишется строчными буквами

**Comment by AkshachRd** [comment]
Все исправил.

**Comment by volgatech-web-development** [comment]
- [x] Еще проблемы с форматированием 
![image](https://user-images.githubusercontent.com/63309827/79016675-43159000-7b78-11ea-98bd-4ea33333f56e.png)

- [x] У классов .first_phrase и .second_phrase нужно выделить общие стили в общий класс, назвать его соответствующе и добавить для обоих <p>
