### ISSUE TITLE
Замечания по лабораторной работе №7 (1 задание)

### ISSUE THREAD

**Issue by volgatech-web-development** [AkshachRd/web-development#2]
- [x] Уехало 
![image](https://user-images.githubusercontent.com/63309827/78864954-6e4b9280-7a45-11ea-9ca5-a1a02b6b113d.png)
+ подключать скрипт не нужно в теге p.

- [x] Файлы названы не по соглашению 

- [x] Подключаем скрипт в head, но с атрибутами defer или async (в чем их отличие почитать в гугле)

- [x] Для чего эти слеши ?
![image](https://user-images.githubusercontent.com/63309827/78865167-cc787580-7a45-11ea-8784-e47eaf68b212.png)

Слеши загрязняют код, они по сути бессмысленны, разделять логически блоки кода можно пустыми строками, так тоже будут видны блоки

**Comment by AkshachRd** [comment]
1)Исправил. Теперь <script> в head.
2)Про слеши написано в [code style](https://learn.javascript.ru/coding-style) , который нам сказали использовать. ![image](https://user-images.githubusercontent.com/29169528/78868116-fc764780-7a4a-11ea-88e0-8b470b2424bd.png)

**Comment by volgatech-web-development** [comment]
- [x]  1 и 0 разве являются простыми или непростыми цифрами ? Выяснить и сделать правильную обработку для них
![image](https://user-images.githubusercontent.com/63309827/79419926-79ac3a00-7fc0-11ea-9c29-38bc7e6c2b8f.png)

**Comment by AkshachRd** [comment]
Исправил.
