### ISSUE TITLE
Замечания по лабораторной работе №7 (2 задание)

### ISSUE THREAD

**Issue by volgatech-web-development** [AkshachRd/web-development#3]
- [x]  ```let l = 0;``` нужно избавиться от глобальной переменной. Переменные нужно объявлять в блоках кода (функции, циклы, условия), в которых они используются, как можно ближе к началу их использования.

- [x] не хватает ;

- [x]  не работает программа
![image](https://user-images.githubusercontent.com/63309827/79420680-16bba280-7fc2-11ea-8d2d-40ef5111bfcb.png)

- [x] пример, который написан в коде, считается не верно, 2*3 = 6, 6-8 = -2, а не 2

**Comment by AkshachRd** [comment]
Исправил.
