### ISSUE TITLE
Замечания по лабораторной работе №2 

### ISSUE THREAD

**Issue by volgatech-web-development** [AkshachRd/web-development#4]
**1 задание**
1.  Для чего используется Dos ? Объяснить.
- [x]  не хватает ;

**2 задание**
- [x]  не хватает ;

**3 задание**
- [x]  Разные подход к именованию переменных. В одном месте начинается со строчных букв, в другом с заглавных
![image](https://user-images.githubusercontent.com/63309827/79421373-58008200-7fc3-11ea-8075-5f79f030932b.png)
- [x]  не хватает ;

**4 задание**
- [x]  не хватает ;
1. Расскажи про реализацию, что происходит в коде и что для чего нужно

**Comment by AkshachRd** [comment]
1) DOS - это подключаемый модуль, в котором, в частности, есть функция GetEnv, которую мне и нужно было использовать.
3)Исправил.
4)Берется строчка от Get запроса. Потом происходит поиск в этой строке другой подстроки, которая  является данным идентификатором. После копируется в отдельную переменную значение этого идентификатора до начала следующего. Выводится идентификатор и его значение на экран.
; отсутствую только перед END, так как это правило форматирование, которого мы должны придерживаться. https://drive.google.com/file/d/1V3Ft688Lgp_ond_S0Itjc_7d-25OL4-6/view?usp=sharing
